{"uuid": "4bb40856-4197-4ec9-a3bc-6da542696d16", "children": ["4be52807-6968-4a8c-8ec8-e8b1bff0faee"], "befores": [{"name": "driver_operation", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F44EB46620>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))\n", "trace": "  File \"D:\\workspace\\Android_UItest\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\workspace\\Android_UItest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\workspace\\Android_UItest\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\workspace\\Android_UItest\\conftest.py\", line 18, in driver_operation\n    driver = webdriver.Remote('http://localhost:4723/wd/hub', desired_caps)\n  File \"D:\\workspace\\Android_UItest\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 229, in __init__\n    super().__init__(\n  File \"D:\\workspace\\Android_UItest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"D:\\workspace\\Android_UItest\\venv\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 319, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)\n  File \"D:\\workspace\\Android_UItest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 433, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"D:\\workspace\\Android_UItest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 344, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"D:\\workspace\\Android_UItest\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 366, in _request\n    response = self._conn.request(method, url, body=body, headers=headers)\n  File \"D:\\workspace\\Android_UItest\\venv\\lib\\site-packages\\urllib3\\request.py\", line 78, in request\n    return self.request_encode_body(\n  File \"D:\\workspace\\Android_UItest\\venv\\lib\\site-packages\\urllib3\\request.py\", line 170, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"D:\\workspace\\Android_UItest\\venv\\lib\\site-packages\\urllib3\\poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"D:\\workspace\\Android_UItest\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"D:\\workspace\\Android_UItest\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"D:\\workspace\\Android_UItest\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 813, in urlopen\n    return self.urlopen(\n  File \"D:\\workspace\\Android_UItest\\venv\\lib\\site-packages\\urllib3\\connectionpool.py\", line 785, in urlopen\n    retries = retries.increment(\n  File \"D:\\workspace\\Android_UItest\\venv\\lib\\site-packages\\urllib3\\util\\retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\n"}, "start": 1658122580415, "stop": 1658122596790}], "start": 1658122580415, "stop": 1658122596963}